export const tickets = [
    {
        "ticketId": "TKT-001",
        "title": "Leaking Kitchen Faucet",
        "createdDate": "2025-11-14T18:50:00",
        "complaintRequest": "The kitchen faucet has been dripping continuously for two days. Water is being wasted.",
        "location": "A-101 - Kitchen",
        "name": "Nimal Perera",
        "complaintCategory": "MEP",
        "jobType": "Plumbing",
        "complaintRecievdBy": "Kasun Bandara",
        "reportedTo": "Sunil Wickramasinghe",
        "completedDate": "2025-11-16T14:30:00",
        "status": "assigned",
        "priority": "high",
        "remarks": "Faucet washer replaced. Issue resolved.",
        "csat": 5
    },
    {
        "ticketId": "TKT-002",
        "title": "AC Not Cooling",
        "createdDate": "2025-11-15T09:20:00",
        "complaintRequest": "The air conditioner in the bedroom is blowing warm air even at the lowest temperature setting.",
        "location": "B-203 - Bedroom",
        "name": "Chamari Fernando",
        "complaintCategory": "MEP",
        "jobType": "Electrical",
        "complaintRecievdBy": "Dilshan Rajapaksa",
        "reportedTo": "Rohan Gunasekara",
        "completedDate": null,
        "status": "in_progress",
        "priority": "medium",
        "remarks": "Technician assigned. Refrigerant level being checked.",
        "csat": null
    },
    {
        "ticketId": "TKT-003",
        "title": "Flickering Corridor Light",
        "createdDate": "2025-11-13T16:10:00",
        "complaintRequest": "The corridor light keeps flickering during the night. Possibly a loose connection.",
        "location": "C-310 - Corridor",
        "name": "Amaya Jayawardena",
        "complaintCategory": "MEP",
        "jobType": "Electrical",
        "complaintRecievdBy": "Nuwan Silva",
        "reportedTo": "Rohan Gunasekara",
        "completedDate": "2025-11-14T10:15:00",
        "status": "closed",
        "priority": "low",
        "remarks": "Loose wiring fixed. Light working normally.",
        "csat": 4
    },
    {
        "ticketId": "TKT-004",
        "title": "Gas Leak Smell",
        "createdDate": "2025-11-14T07:45:00",
        "complaintRequest": "A strong gas smell is present inside the kitchen. This could be dangerous and requires immediate attention.",
        "location": "D-112 - Kitchen",
        "name": "Ravi Dissanayake",
        "complaintCategory": "MEP",
        "jobType": "Plumbing",
        "complaintRecievdBy": "Kasun Bandara",
        "reportedTo": "Sunil Wickramasinghe",
        "completedDate": null,
        "status": "in_progress",
        "priority": "urgent",
        "remarks": "Emergency team dispatched. Gas pipe inspection underway.",
        "csat": null
    },
    {
        "ticketId": "TKT-005",
        "title": "Broken Balcony Door Lock",
        "createdDate": "2025-11-10T11:30:00",
        "complaintRequest": "The lock on the balcony sliding door is broken and not closing properly.",
        "location": "A-205 - Balcony",
        "name": "Meenuka Senanayake",
        "complaintCategory": "Management",
        "jobType": "Civil",
        "complaintRecievdBy": "Dilshan Rajapaksa",
        "reportedTo": "Pradeep Samaraweera",
        "completedDate": "2025-11-12T16:00:00",
        "status": "resolved",
        "priority": "medium",
        "remarks": "Lock mechanism replaced. Door functioning properly.",
        "csat": 5
    },
    {
        "ticketId": "TKT-006",
        "title": "Low Water Pressure",
        "createdDate": "2025-11-16T08:15:00",
        "complaintRequest": "Water pressure is very low in the bathroom. Takes a long time to fill a bucket.",
        "location": "E-408 - Bathroom",
        "name": "Tharaka Wijesinghe",
        "complaintCategory": "MEP",
        "jobType": "Plumbing",
        "complaintRecievdBy": "Nuwan Silva",
        "reportedTo": "Sunil Wickramasinghe",
        "completedDate": null,
        "status": "open",
        "priority": "medium",
        "remarks": "Awaiting plumber availability.",
        "csat": null
    },
    {
        "ticketId": "TKT-007",
        "title": "Loose Door Handle",
        "createdDate": "2025-11-11T14:20:00",
        "complaintRequest": "The main entrance door handle is loose and needs tightening.",
        "location": "B-104 - Main Door",
        "name": "Sanjay Gunaratne",
        "complaintCategory": "Management",
        "jobType": "Civil",
        "complaintRecievdBy": "Kasun Bandara",
        "reportedTo": "Pradeep Samaraweera",
        "completedDate": "2025-11-13T09:45:00",
        "status": "closed",
        "priority": "low",
        "remarks": "Door handle tightened and secured.",
        "csat": 4
    },
    {
        "ticketId": "TKT-008",
        "title": "Noisy Ceiling Fan",
        "createdDate": "2025-11-15T17:30:00",
        "complaintRequest": "Ceiling fan making loud noise and wobbling. Might fall down if not fixed soon.",
        "location": "C-207 - Living Room",
        "name": "Priyanka Mendis",
        "complaintCategory": "MEP",
        "jobType": "Electrical",
        "complaintRecievdBy": "Dilshan Rajapaksa",
        "reportedTo": "Rohan Gunasekara",
        "completedDate": "2025-11-17T11:20:00",
        "status": "resolved",
        "priority": "high",
        "remarks": "Fan blades balanced and mounting bracket tightened.",
        "csat": 3
    },
    {
        "ticketId": "TKT-009",
        "title": "Toilet Flush Not Working",
        "createdDate": "2025-11-12T10:00:00",
        "complaintRequest": "Toilet flush not working properly. Water keeps running continuously.",
        "location": "D-315 - Bathroom",
        "name": "Upul Rathnayake",
        "complaintCategory": "MEP",
        "jobType": "Plumbing",
        "complaintRecievdBy": "Nuwan Silva",
        "reportedTo": "Sunil Wickramasinghe",
        "completedDate": "2025-11-14T15:10:00",
        "status": "closed",
        "priority": "high",
        "remarks": "Flush valve replaced. Working normally now.",
        "csat": 5
    },
    {
        "ticketId": "TKT-010",
        "title": "Peeling Wall Paint",
        "createdDate": "2025-11-16T13:45:00",
        "complaintRequest": "Paint peeling off from the bedroom walls due to dampness.",
        "location": "E-501 - Bedroom",
        "name": "Sanduni Herath",
        "complaintCategory": "Management",
        "jobType": "Civil",
        "complaintRecievdBy": "Kasun Bandara",
        "reportedTo": "Pradeep Samaraweera",
        "completedDate": null,
        "status": "assigned",
        "priority": "low",
        "remarks": "Inspection scheduled for next week.",
        "csat": null
    },
    {
        "ticketId": "TKT-011",
        "title": "Kitchen Exhaust Fan Failure",
        "createdDate": "2025-11-09T07:30:00",
        "complaintRequest": "Kitchen exhaust fan not working. Smoke and smell not getting ventilated.",
        "location": "A-303 - Kitchen",
        "name": "Mahesh Kumara",
        "complaintCategory": "MEP",
        "jobType": "Electrical",
        "complaintRecievdBy": "Dilshan Rajapaksa",
        "reportedTo": "Rohan Gunasekara",
        "completedDate": "2025-11-11T12:00:00",
        "status": "resolved",
        "priority": "medium",
        "remarks": "Motor replaced. Fan working efficiently.",
        "csat": 5
    },
    {
        "ticketId": "TKT-012",
        "title": "Cracked Window Glass",
        "createdDate": "2025-11-17T09:00:00",
        "complaintRequest": "Window glass cracked. Needs replacement before it breaks completely.",
        "location": "B-406 - Bedroom",
        "name": "Achini Perera",
        "complaintCategory": "Management",
        "jobType": "Civil",
        "complaintRecievdBy": "Nuwan Silva",
        "reportedTo": "Pradeep Samaraweera",
        "completedDate": null,
        "status": "open",
        "priority": "high",
        "remarks": "Glass measurements taken. Ordering replacement.",
        "csat": null
    },
    {
        "ticketId": "TKT-013",
        "title": "Water Heater Not Working",
        "createdDate": "2025-11-13T12:40:00",
        "complaintRequest": "Water heater not heating water. Family having to use cold water for bathing.",
        "location": "C-109 - Bathroom",
        "name": "Lakshan Wijemanne",
        "complaintCategory": "MEP",
        "jobType": "Electrical",
        "complaintRecievdBy": "Kasun Bandara",
        "reportedTo": "Rohan Gunasekara",
        "completedDate": "2025-11-15T14:30:00",
        "status": "closed",
        "priority": "high",
        "remarks": "Heating element replaced. Working properly.",
        "csat": 4
    },
    {
        "ticketId": "TKT-014",
        "title": "Blocked Drainage Pipe",
        "createdDate": "2025-11-08T15:20:00",
        "complaintRequest": "Drainage pipe blocked in the kitchen sink. Water not draining at all.",
        "location": "D-208 - Kitchen",
        "name": "Ruwan Sampath",
        "complaintCategory": "MEP",
        "jobType": "Plumbing",
        "complaintRecievdBy": "Dilshan Rajapaksa",
        "reportedTo": "Sunil Wickramasinghe",
        "completedDate": "2025-11-10T10:15:00",
        "status": "resolved",
        "priority": "high",
        "remarks": "Pipe cleaned and blockage removed. Draining properly.",
        "csat": 5
    },
    {
        "ticketId": "TKT-015",
        "title": "Fire Alarm Beeping",
        "createdDate": "2025-11-17T16:00:00",
        "complaintRequest": "Fire alarm beeping continuously. Battery might need replacement.",
        "location": "E-302 - Living Room",
        "name": "Nimali Rodrigo",
        "complaintCategory": "MEP",
        "jobType": "Electrical",
        "complaintRecievdBy": "Nuwan Silva",
        "reportedTo": "Sunil Wickramasinghe",
        "completedDate": null,
        "status": "assigned",
        "priority": "medium",
        "remarks": "Technician will visit tomorrow morning.",
        "csat": null
    },
    {
        "ticketId": "TKT-016",
        "title": "Garbage Collection Issue",
        "createdDate": "2025-11-10T11:00:00",
        "complaintRequest": "Common area garbage not being collected regularly. Bad smell spreading.",
        "location": "Ground Floor - Common Area",
        "name": "Kamal Jayasuriya",
        "complaintCategory": "Management",
        "jobType": "Housekeeping",
        "complaintRecievdBy": "Dilshan Rajapaksa",
        "reportedTo": "Pradeep Samaraweera",
        "completedDate": "2025-11-11T08:30:00",
        "status": "closed",
        "priority": "medium",
        "remarks": "Cleaning schedule revised. Issue resolved.",
        "csat": 3
    },
    {
        "ticketId": "TKT-017",
        "title": "Elevator Malfunction",
        "createdDate": "2025-11-14T13:15:00",
        "complaintRequest": "Elevator making strange sounds and jerking during operation.",
        "location": "Tower B - Elevator",
        "name": "Hasini Wijesekara",
        "complaintCategory": "MEP",
        "jobType": "Mechanical",
        "complaintRecievdBy": "Kasun Bandara",
        "reportedTo": "Rohan Gunasekara",
        "completedDate": null,
        "status": "in_progress",
        "priority": "urgent",
        "remarks": "Maintenance company contacted. Inspection scheduled.",
        "csat": null
    },
    {
        "ticketId": "TKT-018",
        "title": "Parking Barrier Not Working",
        "createdDate": "2025-11-12T16:45:00",
        "complaintRequest": "Parking barrier not opening with access card. Residents unable to enter.",
        "location": "Basement Parking - Entry",
        "name": "Thisara Gamage",
        "complaintCategory": "Management",
        "jobType": "Electrical",
        "complaintRecievdBy": "Nuwan Silva",
        "reportedTo": "Pradeep Samaraweera",
        "completedDate": "2025-11-13T10:30:00",
        "status": "resolved",
        "priority": "high",
        "remarks": "Card reader replaced. System working properly.",
        "csat": 4
    },
    {
        "ticketId": "TKT-019",
        "title": "Ceiling Cracks",
        "createdDate": "2025-11-16T10:20:00",
        "complaintRequest": "Cracks appearing on the living room ceiling. Looks serious.",
        "location": "F-205 - Living Room",
        "name": "Buddhika Amarasinghe",
        "complaintCategory": "Management",
        "jobType": "Civil",
        "complaintRecievdBy": "Dilshan Rajapaksa",
        "reportedTo": "Pradeep Samaraweera",
        "completedDate": null,
        "status": "open",
        "priority": "urgent",
        "remarks": "Structural engineer consultation required.",
        "csat": null
    },
    {
        "ticketId": "TKT-020",
        "title": "Internet Connection Problems",
        "createdDate": "2025-11-15T14:00:00",
        "complaintRequest": "Internet connection dropping frequently. Unable to work from home.",
        "location": "C-412 - Study Room",
        "name": "Anuradha Gunasekara",
        "complaintCategory": "MEP",
        "jobType": "Electrical",
        "complaintRecievdBy": "Kasun Bandara",
        "reportedTo": "Rohan Gunasekara",
        "completedDate": "2025-11-16T16:45:00",
        "status": "closed",
        "priority": "medium",
        "remarks": "Network cable replaced. Connection stable now.",
        "csat": 5
    }
];